version: '2'
services:
    turmas2-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/turmas2/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=turmas2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
